name: hello-world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: Code review
        uses: codacy/codacy-analysis-cli-action@2.2.2
        with:
          files: '**/*.py'
          working-directory: ./ci-cd-testing
          verbose: true


